bairros = [
 "35º BI"
,"Aeroporto"
,"Asa Branca"
,"Aviário"
,"Baraúna"
,"Barro Vermelho"
,"Brasília"
,"Calumbi"
,"Campo do Gado Novo"
,"Campo Limpo"
,"Capuchinhos"
,"Caseb"
,"Cedin"
,"Centro"
,"Chácara São Cosme"
,"Cidade Nova"
,"CIS"
,"Conceição"
,"Coronel José Pinto"
,"Cruzeiro"
,"Dner"
,"Estação Nova"
,"Eucalipto"
,"Gabriela"
,"Jardim Acácia"
,"Jardim Cruzeiro"
,"Jardim Recreio"
,"Kalilândia"
,"Lagoa Grande"
,"Lagoa Salgada"
,"Limoeiro"
,"Mangabeira"
,"Muchila"
,"Muchila II"
,"Najé"
,"Nova Esperança"
,"Novo Horizonte"
,"Olhos d'Água"
,"Pampalona"
,"Papagaio"
,"Parque Éstrela do Oriente"
,"Parque Getúlio Vargas"
,"Parque Ipê"
,"Parque José Martins Campelo"
,"Parque Panorama"
,"Parque Viver"
,"Pedra do Descanso"
,"Pedra Ferrada"
,"Pilão"
,"Ponto Central"
,"Queimadinha"
,"Rua Nova"
,"Santa Mônica"
,"Santo Antônio dos Prazeres"
,"São João"
,"Serraria Brasil"
,"Sim"
,"Sítio Novo"
,"Sobradinho"
,"Subaé"
,"Tomba"
,"Viveiros"
]